name: Generate Changelog
on:
    push:
        tags:
            - "*"
jobs:
    changelog:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Set up Ruby
              uses: actions/setup-ruby@v1
              with:
                ruby-version: '3.x' # Specify your Ruby version

            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: main
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install dependencies
              run: |
                gem install github_changelog_generator

            - name: Generate changelog
              run: github_changelog_generator \
                    -u ${{ github.repository_owner }} \
                    -p ${{ github.event.repository.name }} \
                    --token ${{ secrets.GITHUB_TOKEN }}

            - name: Commit Changelog
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "chore: update changelog"
                  branch: main
                  file_pattern: "CHANGELOG.md"
                  commit_author: "GitHub Action <actions@github.com>"
